name: CI - Test bn Utility

on:
  push:
    branches: [ "main" ]   # watch indentation carefully!

jobs:
  test:                    # a job called 'test'
    runs-on: ubuntu-latest # runs on an Ubuntu runner

    steps:
      - uses: actions/checkout@v4   # checkout your repo code

      - name: Run Tests             # run your test script
        run: ./test_script > test_results.txt

      - name: Upload Test Results   # upload results even if tests fail
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

